### ISSUE TITLE
disnake.TextChannel.create_invite requires `reason` to be bytes while typed as `str`

### ISSUE THREAD

**Issue by MCausc78** [DisnakeDev/disnake#1086]
### Summary

quote_from_bytes

### Reproduction Steps

1. Create a task, which runs every 2 minute.
2. Task is creating invite and posting it using webhook.
3. Getting error:

### Minimal Reproducible Code

```python
        invite = await channel.create_invite( # 77
            reason=why,                       # 78
            max_age=age,                      # 79
            max_uses=0,                       # 80
            temporary=False,                  # 81
            unique=True,                      # 82
        )                                     # 83
        await self.post_invite(invite, why)   # 84
```

### Expected Results

Invite was created succesfully

### Actual Results

```python
D:\Games\Proekti\Python\eohab>py main.py
starting
loaded cogs, start!
Unhandled exception in internal background task 'task_create_invite'.
Traceback (most recent call last):
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\site-packages\disnake\ext\tasks\__init__.py", line 163, in _loop
    await self.coro(*args, **kwargs)
  File "D:\Games\Proekti\Python\eohab\cogs\base.py", line 36, in task_create_invite
    await self.create_invite(None)
  File "D:\Games\Proekti\Python\eohab\cogs\base.py", line 77, in create_invite
    invite = await channel.create_invite(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\site-packages\disnake\abc.py", line 1284, in create_invite
    data = await self._state.http.create_invite(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\site-packages\disnake\http.py", line 307, in request
    headers["X-Audit-Log-Reason"] = _uriquote(reason, safe="/ ")
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 867, in quote
    return quote_from_bytes(string, safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 897, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
Traceback (most recent call last):
  File "D:\Games\Proekti\Python\eohab\main.py", line 41, in <module>
    loop.run_until_complete(task)
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1881, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
  File "C:\Users\mclr\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 812, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

### Intents

`disnake.Intents.default()`

### System Information

```markdown
D:\Games\Proekti\Python\eohab>py -m disnake -v
- Python v3.11.1-final
- disnake v2.8.1-final
    - disnake importlib.metadata: v2.8.1
- aiohttp v3.8.4
- system info: Windows 10 10.0.22000 AMD64
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

`reason` is typed as `str` in documentation

**Comment by shiftinv** [comment]
The error thrown by urllib here is arguably somewhat confusing; `urllib.parse.quote` converts `str` to `bytes` first, so this can really only happen if you pass something that's *not* a `str`.
Try double-checking your code and making sure it's passing a string (or `None`), this isn't a library bug as far as I can tell.
