### ISSUE TITLE
Converting to thread results in an exception

### ISSUE THREAD

**Issue by Kyzegs** [DisnakeDev/disnake#111]
### Summary

I'm using the `disnake.Thread` annotation in my slash command, but the conversion spits out an exception.

### Reproduction Steps

**Reproduction steps**:
1). Create a slash command that has the channels `OptionType`. This option should only allow thread channel types
2). Annotate `disnake.Thread` for your channel/thread parameter
3). Run the command within Discord and pass a thread to it

**Traceback**:
```
Traceback (most recent call last):
  File "C:\Users\Sebastiaan\AppData\Roaming\Python\Python38\site-packages\disnake\ext\commands\params.py", line 253, in convert_argument
    return await argument
  File "C:\Users\Sebastiaan\AppData\Roaming\Python\Python38\site-packages\disnake\ext\commands\converter.py", line 608, in convert
    return GuildChannelConverter._resolve_thread(ctx, argument, "threads", disnake.Thread)
  File "C:\Users\Sebastiaan\AppData\Roaming\Python\Python38\site-packages\disnake\ext\commands\converter.py", line 465, in _resolve_thread
    match = IDConverter._get_id_match(argument) or re.match(r"<#([0-9]{15,20})>$", argument)
  File "C:\Users\Sebastiaan\AppData\Roaming\Python\Python38\site-packages\disnake\ext\commands\converter.py", line 145, in _get_id_match
    return _ID_REGEX.match(argument)
TypeError: expected string or bytes-like object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Sebastiaan\AppData\Roaming\Python\Python38\site-packages\disnake\ext\commands\interaction_bot_base.py", line 1296, in process_application_commands
    await app_command.invoke(interaction)
  File "C:\Users\Sebastiaan\AppData\Roaming\Python\Python38\site-packages\disnake\ext\commands\slash_core.py", line 568, in invoke
    kwargs = await resolve_param_kwargs(self.callback, inter, kwargs)
  File "C:\Users\Sebastiaan\AppData\Roaming\Python\Python38\site-packages\disnake\ext\commands\params.py", line 439, in resolve_param_kwargs
    kwargs[param.param_name] = await param.convert_argument(inter, kwargs[param.param_name])
  File "C:\Users\Sebastiaan\AppData\Roaming\Python\Python38\site-packages\disnake\ext\commands\params.py", line 257, in convert_argument
    raise errors.ConversionError(self.converter, e) from e
disnake.ext.commands.errors.ConversionError: (<bound method ThreadConverter.convert of <disnake.ext.commands.converter.ThreadConverter object at 0x000001DB827B6DF0>>, TypeError('expected string or bytes-like object'))
```

### Minimal Reproducible Code

```python
@commands.slash_command(
    options=[
        disnake.Option(
            name='thread',
            type=disnake.OptionType.channel,
            required=True,
            channel_types=[disnake.ChannelType.public_thread, disnake.ChannelType.private_thread],
        ),
    ],
)
async def test(
    self,
    interaction: disnake.ApplicationCommandInteraction,
    ticket: disnake.Thread,
) -> None:
    pass
```

### Expected Results

The converter should not throw an error.

### Actual Results

The converter throws an error.

### Intents

NA

### System Information

- Python v3.8.6-final
- disnake v2.2.0-beta
    - disnake pkg_resources: v2.2.0 
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by thesadru** [comment]
There's simply no way to detect a slash command was created using the old-style syntax. We'd have to add a whole another flag to the command to allow for this. 
This used to not be a problem, but with the introduction of docstrings as a way to add descriptions to options, conversions had to be enabled even when a `Param` is not provided.

I recommend you completely abandon the old-style syntax since your code would just be
```py
@commands.slash_command()
async def test(
    self,
    interaction: disnake.ApplicationCommandInteraction,
    ticket: disnake.Thread,
) -> None:
    pass
```
