### ISSUE TITLE
disnake error when using python 3.10

### ISSUE THREAD

**Issue by MisileLab** [DisnakeDev/disnake#114]
### Summary

Using disnake with python 3.10 = error

### Reproduction Steps

1. code just simple bot with disnake
2. run it with python 3.10

### Expected Results

Just run with no error

### Actual Results

Error like this
```
/home/teamcloud/.local/lib/python3.10/site-packages/aiohttp/connector.py:964: RuntimeWarning: coroutine 'TCPConnector._resolve_host' was never awaited
  hosts = await asyncio.shield(self._resolve_host(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/home/teamcloud/바탕화면/Cloud/Bot/main.py", line 18, in <module>
    bot.run('token')
  File "/home/teamcloud/.local/lib/python3.10/site-packages/disnake/client.py", line 834, in run
    return future.result()
  File "/home/teamcloud/.local/lib/python3.10/site-packages/disnake/client.py", line 813, in runner
    await self.start(*args, **kwargs)
  File "/home/teamcloud/.local/lib/python3.10/site-packages/disnake/client.py", line 776, in start
    await self.login(token)
  File "/home/teamcloud/.local/lib/python3.10/site-packages/disnake/client.py", line 635, in login
    data = await self.http.static_login(token.strip())
  File "/home/teamcloud/.local/lib/python3.10/site-packages/disnake/http.py", line 423, in static_login
    data = await self.request(Route("GET", "/users/@me"))
  File "/home/teamcloud/.local/lib/python3.10/site-packages/disnake/http.py", line 299, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/home/teamcloud/.local/lib/python3.10/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/teamcloud/.local/lib/python3.10/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/home/teamcloud/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/teamcloud/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/home/teamcloud/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
TypeError: shield() got an unexpected keyword argument 'loop'
```

### Intents

all

### System Information

- Python v3.10.0-final
- disnake v2.2.1-beta
    - disnake pkg_resources: v2.2.1
- aiohttp v3.6.3
- system info: Linux 5.13.0-20-generic #20-Ubuntu SMP Fri Oct 15 14:21:35 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by shiftinv** [comment]
That's a bug in an older version of aiohttp, for Python 3.10 you'll need to upgrade to at least aiohttp 3.7.0 (`pip install aiohttp~=3.7.0`):
https://github.com/aio-libs/aiohttp/commit/0d2ca3f0bce2c0ccbd25f24cdeed77f5b708bb62

**Comment by weerdy15** [comment]
i has the same issue, upgrading aiohttp version helped
thanks @shiftinv
