### ISSUE TITLE
Failed to overwrite slash commands warning.

### ISSUE THREAD

**Issue by Victorsitou** [DisnakeDev/disnake#133]
### Summary

When creating a slash command with params, I get this error: `[WARNING] Failed to overwrite global commands due to Option.__init__() got an unexpected keyword argument 'name_localizations'`. It appears randomly, whether `test_guilds` is used or not.

### Reproduction Steps

Create a simple slash command with a parameter.

When trying to run the command, it just disappears and all other slash commands too. The error seems to appear randomly.

### Minimal Reproducible Code

```python
@bot.slash_command()
async def test(
    inter: disnake.ApplicationCommandInteraction,
    text: str,
):
    await inter.response.send_message(text)
```

### Expected Results

Slash commands to work properly.

### Actual Results

Slash commands disappear.

### Intents

None

### System Information

- Python v3.10.0-final
- disnake v2.2.1-beta (PyPI version)
    - disnake pkg_resources: v2.2.1
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I have tried reproducing the error with the GitHub version, and it seems to be working fine.

If someone could reproduce this error, I would appreciate it.

**Comment by Victorsitou** [comment]
Here is the full trace back (Thanks to m1raynee)
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\disnake\ext\commands\interaction_bot_base.py", line 723, in _sync_application_commands
    await self.bulk_overwrite_guild_commands(guild_id, to_send)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\disnake\client.py", line 2219, in bulk_overwrite_guild_commands
    return await self._connection.bulk_overwrite_guild_commands(guild_id, application_commands)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\disnake\state.py", line 1778, in bulk_overwrite_guild_commands
    commands = [application_command_factory(data) for data in results]
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\disnake\state.py", line 1778, in <listcomp>
    commands = [application_command_factory(data) for data in results]
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\disnake\app_commands.py", line 68, in application_command_factory
    return SlashCommand.from_dict(data)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\disnake\app_commands.py", line 429, in from_dict
    payload["options"] = [Option.from_dict(p) for p in payload["options"]]
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\disnake\app_commands.py", line 429, in <listcomp>
    payload["options"] = [Option.from_dict(p) for p in payload["options"]]
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\disnake\app_commands.py", line 230, in from_dict
    return Option(**payload)
TypeError: __init__() got an unexpected keyword argument 'name_localizations' 
```
