### ISSUE TITLE
Callback for 'ask' command missing 'ctx' parameter.

### ISSUE THREAD

**Issue by CalebEevee** [DisnakeDev/disnake#201]
### Summary

The confirm button example is incorrect - it does not work.

### Reproduction Steps

Copy and pasted disnake/examples/views/button/confirm.py in two different files - the class and the command in two different files.
Then, I imported the file (and class). When I ran the command, I got an error.

### Minimal Reproducible Code

```python
import disnake
from disnake.ext import commands



class Confirm(disnake.ui.View):
    def __init__(self):
        super().__init__()
        self.value = None

    # When the confirm button is pressed, set the inner value to `True` and
    # stop the View from listening to more input.
    # We also send the user an ephemeral message that we're confirming their choice.
    @disnake.ui.button(label="Confirm", style=disnake.ButtonStyle.blurple)
    async def confirm(ctx: commands.Context, self, button: disnake.ui.Button, interaction: disnake.MessageInteraction):
        await interaction.response.send_message("Confirming", ephemeral=True)
        self.value = True
        self.stop()

    # This one is similar to the confirmation button except sets the inner value to `False`
    @disnake.ui.button(label="Cancel", style=disnake.ButtonStyle.grey)
    async def cancel(ctx: commands.Context, self, button: disnake.ui.Button, interaction: disnake.MessageInteraction):
        await interaction.response.send_message("Cancelling", ephemeral=True)
        self.value = False
        self.stop()


# This is in another file

    @bot.command()
    async def ask(ctx: commands.Context):
      """Asks the user a question to confirm something."""
      # We create the view and assign it to a variable so we can wait for it later.
      view = Confirm()
      await ctx.send("Do you want to continue?", view=view)
      # Wait for the View to stop listening for input...
      await view.wait()
      if view.value is None:
          print("Timed out...")
      elif view.value:
          print("Confirmed...")
      else:
          print("Cancelled...")
```

### Expected Results

I expected the buttons to be made. However, it gave me an error.

### Actual Results

I got a traceback error.

## Traceback Error
```py
Ignoring exception in on_message
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/disnake/ext/commands/core.py", line 752, in _parse_arguments
    next(iterator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/disnake/client.py", line 505, in _run_event
    await coro(*args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/disnake/ext/commands/bot_base.py", line 600, in on_message
    await self.process_commands(message)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/disnake/ext/commands/bot_base.py", line 597, in process_commands
    await self.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/disnake/ext/commands/bot_base.py", line 560, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/disnake/ext/commands/core.py", line 921, in invoke
    await self.prepare(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/disnake/ext/commands/core.py", line 855, in prepare
    await self._parse_arguments(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/disnake/ext/commands/core.py", line 754, in _parse_arguments
    raise disnake.ClientException(
disnake.errors.ClientException: Callback for ask command is missing "ctx" parameter.
```

### Intents

all intents

### System Information

```yaml
- Python v3.8.12-final
- disnake v2.2.2-beta
    - disnake pkg_resources: v2.2.2
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0-1023-gcp #25~20.04.1-Ubuntu SMP Mon Nov 15 15:54:39 UTC 2021
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by thesadru** [comment]
You forgot to add a `self` parameter to the view methods.

**Comment by CalebEevee** [comment]
> You forgot to add a `self` parameter to the view methods.

Thank you - Maybe the examples should be updated to include this - I copy-pasted directly from the examples.

**Comment by NESTOWL** [comment]
> > You forgot to add a `self` parameter to the view methods.
> 
> Thank you - Maybe the examples should be updated to include this - I copy-pasted directly from the examples.

I think you should teach OOP, that's all 😳👍
