### ISSUE TITLE
event.fetch_users() only accepts with_members as a string, not bool

### ISSUE THREAD

**Issue by djee-dev** [DisnakeDev/disnake#271]
### Summary

event.fetch_users() only accepts with_members as a string, not bool

### Reproduction Steps

```py
'Will throw an error'
await event.fetch_users(with_members=True)

'Will throw another error, but accepts with_members'
await event.fetch_users(with_members=str(True))
```

### Expected Results

List of users who are interested in an Event

### Actual Results

```ps
Traceback (most recent call last):
  File "lib\site-packages\disnake\ext\commands\slash_core.py", line 585, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "lib\site-packages\disnake\ext\commands\params.py", line 678, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "lib\site-packages\disnake\utils.py", line 555, in maybe_coroutine
    return await value
  File "cogs\getevent.py", line 42, in getevent
    subs = await event.fetch_users(with_members=True)
  File "lib\site-packages\disnake\guild_scheduled_event.py", line 414, in fetch_users
    raw_users = await self._state.http.get_guild_scheduled_event_users(
  File "lib\site-packages\disnake\http.py", line 320, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "lib\site-packages\aiohttp\client.py", line 492, in _request
    req = self._request_class(
  File "lib\site-packages\aiohttp\client_reqrep.py", line 283, in __init__
    url2 = url.with_query(params)
  File "lib\site-packages\yarl\_url.py", line 984, in with_query
    new_query = self._get_str_query(*args, **kwargs)
  File "lib\site-packages\yarl\_url.py", line 945, in _get_str_query
    query = "&".join(self._query_seq_pairs(quoter, query.items()))
  File "lib\site-packages\yarl\_url.py", line 908, in _query_seq_pairs
    yield quoter(key) + "=" + quoter(cls._query_var(val))
  File "lib\site-packages\yarl\_url.py", line 923, in _query_var
    raise TypeError(
TypeError: Invalid variable type: value should be str, int or float, got True of type <class 'bool'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\site-packages\disnake\ext\commands\interaction_bot_base.py", line 1346, in process_application_commands
    await app_command.invoke(interaction)
  File "lib\site-packages\disnake\ext\commands\slash_core.py", line 594, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Invalid variable type: value should be str, int or float, got True of type <class 'bool'>

```

### Intents

guilds, members, reactions

### System Information

```ps
- Python v3.10.0-final
- disnake v2.3.0-beta
    - disnake pkg_resources: v2.3.0
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Edit: Fixed error message

**Comment by djee-dev** [comment]
PS: Pasted the wrong error in.
The error posted comes from:
```py
await event.fetch_users(with_members=str(True))
```
