### ISSUE TITLE
Union Type in Slash Param

### ISSUE THREAD

**Issue by devRMA** [DisnakeDev/disnake#282]
### Summary

Slash parameter not working with union types

### Reproduction Steps

I just updated disnake, and my command stopped working.
I used an old version (can't say which one exactly) and my command worked, so I updated disnake, and the command stopped working.

### Minimal Reproducible Code

```python
@bot.slash_command()
async def test(
    inter: disnake.CommandInteraction,
    user: disnake.Member | disnake.User
):
    ...
```

or
```python
from typing import Union

@bot.slash_command()
async def test(
    inter: disnake.CommandInteraction,
    user: Union[disnake.Member, disnake.User]
):
    ...
```

### Expected Results

That a slash was created, where it was possible to receive a Member object or a User object

### Actual Results

```
Traceback (most recent call last):
   File "/usr/src/androxus/main.py", line 42, in <module>
     async def test(
   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/interaction_bot_base.py", line 486, in decorator
     result = slash_command(
   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 669, in decorator
     return InvokableSlashCommand(
   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 363, in __init__
     options = expand_params(self)
   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/params.py", line 780, in expand_params
     _, inter_param, params, injections = collect_params(command.callback)
   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/params.py", line 692, in collect_params
     paraminfo = ParamInfo.from_param(parameter, {}, doc)
   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/params.py", line 384, in from_param
     self.parse_annotation(type_hints.get(param.name, param.annotation))
   File "/usr/local/lib/python3.10/site-packages/disnake/ext/commands/params.py", line 483, in parse_annotation
     if issubclass(annotation, LargeInt):
 TypeError: issubclass() arg 1 must be a class
 ```

### Intents

all

### System Information

```shell
$ python -m disnake -v

- Python v3.10.2-final
- disnake v2.3.0-beta
    - disnake pkg_resources: v2.3.0
- aiohttp v3.8.1
- system info: Linux 5.15.12-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:08:07 UTC 2021
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I would like to make this Union Type in the parameter, because I prefer to receive a member, to get his information on the server that the command was used, but I also don't want the command to stop working, if a normal user is passed.

**Comment by Victorsitou** [comment]
This bug was introduced in c4c18582da69747d35004ddad88ecb4348ac897f, thank you for creating the issue.

#283 should fix this.
