### ISSUE TITLE
__init__() got an unexpected keyword argument 'style' buttons

### ISSUE THREAD

**Issue by KarsonTheFoxx** [DisnakeDev/disnake#589]
### Summary

i was making a button and when i try to give it a style or a label i get this error

### Reproduction Steps

i dont know, i've made a button like this before

### Minimal Reproducible Code

```python
accept_button = disnake.Button(style=disnake.ButtonStyle, label="Accept")
```

### Expected Results

a button

### Actual Results

Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'
Ignoring exception in slash command 'verify':
Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 680, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/params.py", line 817, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/utils.py", line 580, in maybe_coroutine
    return await value
  File "/home/foxx/python/OriginsBot/cogs/verify.py", line 50, in verify
    accept_button = disnake.Button(style=disnake.ButtonStyle)
TypeError: __init__() got an unexpected keyword argument 'style'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1264, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/foxx/.local/lib/python3.9/site-packages/disnake/ext/commands/slash_core.py", line 689, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'style'

### Intents

N/A

### System Information

```markdown
- Python v3.9.2-final
- disnake v2.5.1-final
    - disnake pkg_resources: v2.5.1
- aiohttp v3.7.4.post0
- system info: Linux 5.10.110-15808-ge5740beba59b #1 SMP PREEMPT Wed Jun 8 19:18:22 PDT 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by onerandomusername** [comment]
The class you are trying to construct is [disnake.ui.Button](https://docs.disnake.dev/en/stable/api.html#disnake.ui.Button). Please [join the discord](https://discord.gg/disnake) if you require more assistance.

**Comment by KarsonTheFoxx** [comment]
oh, i was just being stupid

**Comment by onerandomusername** [comment]
No worries, happens to the best of us :D
