### ISSUE TITLE
Incorrect gateway logging leads to unhandled exceptions

### ISSUE THREAD

**Issue by Skelmis** [DisnakeDev/disnake#940]
### Summary

If a certain condiction is hit within the gateway, one can force the logging module to produce what appears to be an unhandled error and crash the bot's process

### Reproduction Steps

If you hit https://github.com/DisnakeDev/disnake/blob/master/disnake/gateway.py#L228 then the log message gets an extra variable `stack` included, however when it is output on line https://github.com/DisnakeDev/disnake/blob/master/disnake/gateway.py#L230 that variable is not included which leads to the following.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/disnake/gateway.py", line 247, in run
    _log.warning(msg, self.shard_id, total)
Message: 'Shard ID %s heartbeat blocked for more than %s seconds.\nLoop thread traceback (most recent call last):\n  File "/bot/main.py", line 61, in <module>\n    asyncio.run(run_bot())\n  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete\n    self.run_forever()\n  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever\n    self._run_once()\n  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1906, in _run_once\n    handle._run()\n  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run\n    self._context.run(self._callback, *self._args)\n  File "/usr/local/lib/python3.10/site-packages/disnake/shard.py", line 171, in worker\n    await self.ws.poll_event()\n  File "/usr/local/lib/python3.10/site-packages/disnake/gateway.py", line 691, in poll_event\n    await self.received_message(msg.data)\n  File "/usr/local/lib/python3.10/site-packages/disnake/gateway.py", line 554, in received_message\n    _log.debug("For Shard ID %s: WebSocket Event: %s", self.shard_id, msg)\n'
Arguments: (0, 10)
```

This will also stop the keep alive handler for the bot.

### Expected Results

It doesnt throw an unhandled exception and stop the keep alive handler

### Actual Results

It throws and stops the keep alive handler and errors to output

### Intents

N/A

### System Information

```markdown
Applicable on master
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Skelmis** [comment]
Following up on this, it appears to be an issue with the `stack` itself including a logging call internally. Therefore the `warning` logger sees the debug log call in the traceback and goes yup, sounds good to me I will interpret that because its within the f string
